name: fluttermaps
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.33
  geolocator: ^5.3.1
  flutter_spinkit: ^4.1.2+1
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
  geocoding: ^1.0.4+1
  geocoding_platform_interface: ^1.0.1+1
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

